spring:
  application:
    name: bookreads
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.23bb7fb4cdba7c95
            clientSecret: 1dd9ace680eba71cf63d441ddfa3c26d9010ed6a
# We must set up one application for OAuth in github from Developer settings
# Need to put appropriate clientId & clientSecret here


  data:
    cassandra:
      keyspace-name: main
      username: 'TkNyjHoxneaGjYZKoeytlZYK'
      password: ',HSlpDtJF4b+bYBrfkn.QDC47D1P24qw6aK76Y7O-TbJnZS7hlb-G.W63rGT-WZQvKXeZLy,zhKs_._cvDBlyyJoXwwth_9HUBNin0zBwfYDJR980lz,peTFURkbqu8.'
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: secure-connect-bookreads.zip  #Providing relative path because file is in classpath

astra.db:
  id: 0fc994d9-731e-46f4-96f9-0d6f902aa015-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:TkNyjHoxneaGjYZKoeytlZYK:bb52cd783b007060862829c12af4a34f233b6b4928638e95bff37943c7c8757c
